# Generated by Django 2.1.3 on 2018-12-30 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.TextField(primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('queued', 'queued'), ('processing', 'processing'), ('ready', 'ready'), ('error', 'error')], default='queued', max_length=14)),
            ],
        ),
    ]
