# Generated by Django 2.1.8 on 2019-05-18 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='endpoint',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='tasks',
            name='error_type',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='tasks',
            name='params',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='tasks',
            name='stacktrace',
            field=models.TextField(null=True),
        ),
    ]
