# Generated by Django 2.1.5 on 2019-02-27 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_auto_20190227_2125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='end_t',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='processing_start_t',
            field=models.DateTimeField(null=True),
        ),
    ]
