# Generated by Django 2.1.5 on 2019-02-26 12:51

import api.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api', '0001_create_superuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='Email',
            fields=[
                ('hash', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('verified', models.BooleanField(default=False)),
                ('verification_string', models.CharField(db_index=True, default=api.utils.randhex256, max_length=256)),
            ],
        ),
    ]
