# Generated by Django 2.1.5 on 2019-03-03 13:32

import api.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Email',
            fields=[
                ('hash', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('verified', models.BooleanField(default=False)),
                ('verification_string', models.CharField(db_index=True, default=api.utils.randhex256, max_length=256)),
                ('verification_emails_sent', models.IntegerField(default=0)),
                ('last_verification_email_sent_time', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
